### ISSUE TITLE
Security Groupについて、SSHを閉じて同一SG内でのレプリケーションを許可したい

### ISSUE THREAD

**Issue by yamatada-ya** [inagozeixd/toN#1]
## 概要

EC2やDBについて、SG設定を厳しくしたいです。
具体的には、
- セッションマネージャーの使用を前提として0.0.0.0/0のSSH許可を外す
- replica → sourceに対する3306を許可する
が果たされていればいったん必要十分な通信はできると思われます。

## 完了条件

- [ ] DBの入るSGがSSHを許可していないこと
- [ ] DBがレプリケーションを行えるSG設定になっていること

**Comment by inagozeixd** [comment]
> DBの入るSGがSSHを許可していないこと
> DBがレプリケーションを行えるSG設定になっていること

上記対応が完了したためクローズとします
